Fix potential too long LoadBalancer name
ironcore-dev/cloud-provider-ironcore pull request #459
Opened 2024-10-16 13:28 UTC by ushabelgur

# Proposed Changes

- Fix potential too long LoadBalancer name by deriving loadbalancer name from Service UID
- Handle backwards compatibility by checking for existing LB object with legacy name 
- Add test case for LB with legacy name

Fixes #457

2024-10-24 08:16 UTC, afritzler requested changes

2024-10-24 08:16 UTC, afritzler commented on pkg/cloudprovider/ironcore/load_balancer.go
> +	if err := o.ironcoreClient.Get(ctx, client.ObjectKey{Namespace: o.ironcoreNamespace, Name: legacyLoadBalancerName}, existingLoadBalancer); err == nil {
Can we catch the `NotFound` error here and set the correct UID based name? Also please ensure that all non `NotFound` errors are properly handled.

2024-10-24 09:54 UTC, ushabelgur commented on pkg/cloudprovider/ironcore/load_balancer.go
> +	if err := o.ironcoreClient.Get(ctx, client.ObjectKey{Namespace: o.ironcoreNamespace, Name: legacyLoadBalancerName}, existingLoadBalancer); err == nil {
> Can we catch the `NotFound` error here and set the correct UID based name? Also please ensure that all non `NotFound` errors are properly handled.

In any case we cannot return error from this method as per the method signature, should we just log the error and return empty in case any other error other than `NotFound` ? but again returning empty doesn't really make sense so i was returning new name formed with service Id, and rest of the flow will handle if LB is not found even with this new name.

2024-10-24 10:42 UTC, afritzler commented on pkg/cloudprovider/ironcore/load_balancer.go
> +	if err := o.ironcoreClient.Get(ctx, client.ObjectKey{Namespace: o.ironcoreNamespace, Name: legacyLoadBalancerName}, existingLoadBalancer); err == nil {
Yes, logging the error would be great here. That way we can see if something went wrong (e.g. wrong authentication, networking issues, etc.).

The problem now is what if there is a legacy name in the cluster but we could not get it due to some networking issues? Logging the error and returning an empty string which has to be correctly handled up the call stack is of course needed.

2024-10-30 08:30 UTC, afritzler approved these changes

2024-10-30 08:30 UTC, merged