bump k8s.io dependency to v0.31.0
ironcore-dev/cloud-provider-ironcore pull request #481
Opened 2024-12-23 07:31 UTC by ushabelgur

# Proposed Changes

- Bump k8s.io dependency upgrade to v0.31.0
- Bump controller-runtime to v0.19.0
- Bump golangci-lint to 1.62
- Bump ironcore to point to Machine `NetwrokInterfaceStatus` related changes  
  /ref https://github.com/ironcore-dev/ironcore/pull/1201
- Refer IPs and VIPs from Machine `NetwrokInterfaceStatus`'s  `NetworkInterface` 

Fixes #

2025-01-09 12:53 UTC, afritzler requested changes

2025-01-09 12:53 UTC, afritzler commented on Makefile
> -		test -s $(LOCALBIN)/setup-envtest || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
Can we keep the `latest` version here.

2025-01-10 05:52 UTC, ushabelgur commented on Makefile
> -		test -s $(LOCALBIN)/setup-envtest || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
done reverted the changes

2025-01-15 16:30 UTC, afritzler approved these changes

2025-01-15 16:30 UTC, merged